POST http://localhost:3001/api/users
Content-Type: application/json

{
  "correo": "correo@correo.com",
  "password": "correo",
  "nombre": "correo",
  "apellido": "correo",
  "telefono": "0123456789"
}
