export { authService } from "./auth";
export { canchasService } from "./canchas";
export { deportivosService } from "./deportivos";
export { equiposService } from "./equipos";
export { estadosService } from "./estados";
export { eventosService } from "./eventos";
export { formatosService } from "./formatos";
export { jugadoresService } from "./jugadores";
export { usuariosService } from "./usuarios";
