GET http://localhost:3001/api/users/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJjb3JyZW9AY29ycmVvLmNvbSIsImlkIjoxLCJpYXQiOjE2NjYyMTg0MDl9.OdJfIByTp3Ix_mIo8HPEpoxl5G7eQ31VU40qVi_-D
