GET http://localhost:3001/api/users/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJjb3JyZW9AY29ycmVvLmNvbSIsImlkIjoxLCJpYXQiOjE2NjYyMjQ5ODR9.QvE8TJ00MJ4hgT7ORZV5fxOFKLFlre5puE4uULcZwYQ
